spring:
  application:
    name: architrave
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jwt:
    secret: ${SPRING_JWT_SECRET}
    expiration: ${SPRING_JWT_EXPIRE}
    refresh-token:
      expiration: ${SPRING_JWT_REFRESH_EXPIRE}

  aws:
    region: ${SPRING_AWS_REGION}
    s3:
      bucket-name: ${SPRING_AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${SPRING_AWS_ACCESS_KEY_ID}
      secret-key: ${SPRING_AWS_SECRET_ACCESS_KEY}
